# -*- coding: utf-8 -*-
"""AnaliseDeVoo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11xZaNnOnSrsSIy4BV0LMzzEYTY5p24ZM
"""

pip install pandas

pip install matplotlib

pip install numpy



"""Exploração dos dados

"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('Flights.csv')
#print(df.head(10))

print(df.info())

#checando se há valores nulos
print(df.isnull().sum())

#descrevendo os dados
print(df.describe().round(2))

#dados categóricos
print(df['Origin'].value_counts().head(10))

#identificando todos os valores distintos em uma coluna
print(df['Origin'].unique())

#identificando quantos valores distintos existem
print(df['Origin'].nunique())

"""Filtragem de dados

"""

#Cenário 1: Extrair registros de voos do ano 2000
df['Year'] = df['Fly Date'].astype(str).str.slice(0, 4)
voos2000 = df[df['Year'] == '2000']
print(voos2000)

#Cenário 2: encontrar voos que não incluam LAX como origem
no_lax = df[~df['Origin'].isin(['LAX'])]
print(no_lax)

#Cenário 3: todos os voo que tem LAX como origem
lax = df[df['Origin'].isin(['LAX'])]
print(lax)

